server.error.include-stacktrace=never

spring.ai.google.genai.api-key=${GOOGLE_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

logging.file.name=logs/api.log
logging.level.root=INFO
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30